# kernel/tasks/task.py

"""
Task Model for AI Work OS

Users do not call agents directly.
Users create work.

Tasks are scheduled and executed by worker nodes.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional


# -----------------------------
# ENUMS
# -----------------------------

class TaskStatus(str, Enum):
    CREATED = "created"
    QUEUED = "queued"
    CLAIMED = "claimed"
    RUNNING = "running"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"

class TaskPriority(int, Enum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3


class TaskDomain(str, Enum):
    OPERATIONS = "operations"
    MARKETING = "marketing"
    RESEARCH = "research"
    GENERAL = "general"


# -----------------------------
# OBJECTIVE PRIMITIVE
# -----------------------------

@dataclass
class Objective:
    """
    Core semantic primitive of work.

    Action → applied to → Subject → to achieve → Outcome
    """

    action: str
    subject: str
    outcome: Optional[str] = None

    def to_string(self) -> str:
        if self.outcome:
            return f"{self.action} {self.subject} to {self.outcome}"
        return f"{self.action} {self.subject}"


# -----------------------------
# TASK MODEL
# -----------------------------


@dataclass
class Task:
    """
    Persistent work object within the AI Work OS.
    """

    # core work definition
    objective: Objective
    domain: TaskDomain
    created_by: str

    # routing / ownership
    owner_worker: Optional[str] = None

    # scheduling
    priority: TaskPriority = TaskPriority.MEDIUM
    status: TaskStatus = TaskStatus.CREATED

    # expected outputs
    expected_outputs: List[str] = field(default_factory=list)
    
    # work estimation / timing / dependency hints
    expected_token_count: Optional[int] = None
    due_date: Optional[datetime] = None
    dependency_str: Optional[str] = None
    
    # task relationships
    parent_task_id: Optional[str] = None
    dependencies: List[str] = field(default_factory=list)
    
    # system metadata
    task_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    
    # artifacts generated
    artifacts: List[str] = field(default_factory=list)
    
    # conversation linkage
    thread_id: Optional[str] = None

    # work request linkage
    work_request_id: Optional[str] = None
    intent_index: Optional[int] = None

    # -----------------------------
    # TASK METHODS
    # -----------------------------

    def assign_worker(self, worker_name: str):
        """Assign task to a worker node."""
        self.owner_worker = worker_name
        self.updated_at = datetime.utcnow()

    def update_status(self, new_status: TaskStatus):
        """Update task status."""
        self.status = new_status
        self.updated_at = datetime.utcnow()

    def add_artifact(self, artifact_id: str):
        """Register artifact generated by this task."""
        self.artifacts.append(artifact_id)
        self.updated_at = datetime.utcnow()

    def to_dict(self) -> dict:
        """Serialize task for storage."""
        return {
            "task_id": self.task_id,
            "objective": {
                "action": self.objective.action,
                "subject": self.objective.subject,
                "outcome": self.objective.outcome,
            },
            "domain": self.domain.value,
            "status": self.status.value,
            "priority": self.priority.value,
            "owner_worker": self.owner_worker,
            "created_by": self.created_by,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "expected_outputs": self.expected_outputs,
            "expected_token_count": self.expected_token_count,
            "due_date": self.due_date.isoformat() if self.due_date else None,
            "dependency_str": self.dependency_str,
            "dependencies": self.dependencies,
            "parent_task_id": self.parent_task_id,
            "artifacts": self.artifacts,
            "thread_id": self.thread_id,
            "work_request_id": self.work_request_id,
            "intent_index": self.intent_index,
        }